services:
  - type: web
    name: dentlink
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PGHOST
        fromDatabase:
          name: dentlink-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: dentlink-db
          property: port
      - key: PGUSER
        fromDatabase:
          name: dentlink-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: dentlink-db
          property: password
      - key: PGDATABASE
        fromDatabase:
          name: dentlink-db
          property: database

databases:
  - name: dentlink-db
    databaseName: dentlink
    plan: free
